sudo: required
language: python
services:
  - docker
env:
    # Ref: https://hub.docker.com/r/_/fedora/
    # - CONTAINER_IMAGE=fedora:24
    # - CONTAINER_IMAGE=fedora:latest
    - CONTAINER_IMAGE=fedora:rawhide
install: true
script:
  - scripts/run-in-container.sh scripts/build.sh check-all
