sudo: required
language: python
services:
  - docker
env:
    # Ref: https://hub.docker.com/r/_/fedora/
    # - DOCKER_IMAGE=fedora:24
    # - DOCKER_IMAGE=fedora:latest
    - DOCKER_IMAGE=fedora:rawhide
# Skip install section.
install: true
script:
  - scripts/travis.sh
