#!/bin/sh

#export CPPFLAGS="-I/`rpm --eval %{_includedir}`/libdb `pkg-config --cflags nss`"

export LDFLAGS="-L/usr/lib64/libdb"
export CFLAGS="-O2 -g"

./autogen.sh --noconfigure && \
./configure \
	--with-hackingdocs \
	--build=x86_64-unknown-linux-gnu \
	--prefix=/usr \
	--libdir=/usr/lib64 \
	--sysconfdir=/etc \
	--localstatedir=/var \
	--enable-python \
	--with-external-db \
	--without-apidocs \
	--with-cap \
	--with-lua \
	--with-archive \
	--with-magic \
	--with-archive \
	--without-selinux $* && \
#	--enable-ndb \
make -j8
